// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBaYaopwR1XmmcodTVcEtKSgSusaPdkK8',
    appId: '1:393288360776:web:828205d743ff7449fb097d',
    messagingSenderId: '393288360776',
    projectId: 'classfocus-app',
    authDomain: 'classfocus-app.firebaseapp.com',
    storageBucket: 'classfocus-app.firebasestorage.app',
    measurementId: 'G-9Y5E355LZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy_sWsavwbgHNqjb200EpwgaOeZDf2kfA',
    appId: '1:393288360776:android:d0db1f9c1a105fd2fb097d',
    messagingSenderId: '393288360776',
    projectId: 'classfocus-app',
    storageBucket: 'classfocus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN_oLxoBXCUQ_hbHBzSE6kwzv_po79x_8',
    appId: '1:393288360776:ios:2d6a482cada1098ffb097d',
    messagingSenderId: '393288360776',
    projectId: 'classfocus-app',
    storageBucket: 'classfocus-app.firebasestorage.app',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN_oLxoBXCUQ_hbHBzSE6kwzv_po79x_8',
    appId: '1:393288360776:ios:2d6a482cada1098ffb097d',
    messagingSenderId: '393288360776',
    projectId: 'classfocus-app',
    storageBucket: 'classfocus-app.firebasestorage.app',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBaYaopwR1XmmcodTVcEtKSgSusaPdkK8',
    appId: '1:393288360776:web:c374e77afa8bdf1efb097d',
    messagingSenderId: '393288360776',
    projectId: 'classfocus-app',
    authDomain: 'classfocus-app.firebaseapp.com',
    storageBucket: 'classfocus-app.firebasestorage.app',
    measurementId: 'G-BHWJXRBD2D',
  );
}
